### ISSUE TITLE
Very good job

### ISSUE THREAD

**Issue by besanur** [kamilkirdi/AwqatSalah.Api#2]
Selamunaleyküm Degerli abicim,

tevafuk oldu bugün tekrar arama yapinca böyle bir API oldugunu gördüm cok güzel bir calisma, bu alanda Diyanet den hep bir adim bekliyordum ve sonunda bir ilerlemenin olmasi beni cok memnun etti. Benim kendi sahsima bir calisma var, smart home ile ugrasiyorum. Yurt disinda yasadigim icin burda ezan sesine hasretiz.

Bugünün imkanlariyla cok sey mümkün elhamduilllah bunu iyi yönde kullanabiliyoruz. Github sayfamda bakabilirsiniz bir eklentim var diyanetin sayfasindan namaz vakitlerinin verilerini okuyup 30 günlügüne kayit ediyorum. Bu bana ne icinmi lazim? 
Evimde farkli sekilde namaz vakitlerini gösterme imkani sunuyor bana. 

![20230214_123003](https://user-images.githubusercontent.com/7067485/218853058-c33214b7-768e-434f-bc5d-5dbf4469bf36.jpg)

Veya namaz vakti girdigi an Chromecast ile televizyonumda ezan okutabiliyorum. 

Diyanet APi sini kullanmam benim yapmis oldugum Home Assistant eklentisi icin uymayabilir, cünkü tek kullanici ile farkli kisiler addonu kullanacagi icin biraz limite ulasabilir. Belki bir cüzümü vardir.

Faydam olacaksa menuniyetle yardim etmek isterim.

**Comment by kamilkirdi** [comment]
Aleykümselam. Öncelikle çalışman için tebrik ederim. Gerçekten çok hoş olmuş. Kotaya takılma hususundaki endişene gelirsek, bunu aşmanın 2 yolu var;
1. Bu repoyu windows/linux herhangi bir sunucuya publish ederek kulandığında, senin clientlerin de bu yeni sunucudan yayın yapan apiyi tüketirse, aynı yeri 1000 defa çeksen bile bu repo Diyanet AwqatSalah servisine 1 defa gideceği için problem yaşamazsın.
2. Kullanıcıların Diyanet AwqatSalah api servisinden kendi adlarına kullanıcı alır ve sisteme bu kullanıcı adı ve şifreleri ile giriş yaparlarsa yine bir problemin kalmaz.
Selam ve dua ile...
