### ISSUE TITLE
Five request limit

### ISSUE THREAD

**Issue by meezaan** [kamilkirdi/AwqatSalah.Api#4]
Salaam, thank you for this.

Exactly what is the limit? 5 requests per day? 5 requests the life of each token?

The documentation is not exactly clear, so any information you can provide will be helpful.

Thank you.

**Comment by ramazansancar** [comment]
https://awqatsalah.diyanet.gov.tr/files/56d83ac4-f7f5-4f6e-9b9e-b1ffeebf1b6a.pdf

@meezaan It is stated here that there is a daily limit of 5. **Page: 6**

**Comment by meezaan** [comment]
> https://awqatsalah.diyanet.gov.tr/files/56d83ac4-f7f5-4f6e-9b9e-b1ffeebf1b6a.pdf
> 
> @meezaan It is stated here that there is a daily limit of 5. **Page: 6**

Thank you.
